[project]
name = "iska-python-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fabric-cicd>=0.1.25",
    "ms-fabric-cli>=1.0.1",
]
